/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg0816_.pkg6;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Formando Tarde
 */
public class Voo extends javax.swing.JFrame {

    /**
     * Creates new form Voo
     */
    public Voo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        partidaH = new javax.swing.JLabel();
        partidaM = new javax.swing.JLabel();
        partidaTxtH = new javax.swing.JTextField();
        partidaTxtM = new javax.swing.JTextField();
        duracaoTxtH = new javax.swing.JTextField();
        duracaoTxtM = new javax.swing.JTextField();
        duracaoH = new javax.swing.JLabel();
        duracaoM = new javax.swing.JLabel();
        chegadaH = new javax.swing.JLabel();
        chegadaM = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        chegadaTxtM = new javax.swing.JLabel();
        chegadaTxtH = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        msgFinal = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Duração");

        partidaH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        partidaH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        partidaH.setText("Horas");

        partidaM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        partidaM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        partidaM.setText("Minutos");

        partidaTxtH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        partidaTxtH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        partidaTxtH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partidaTxtHActionPerformed(evt);
            }
        });
        partidaTxtH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                partidaTxtHKeyPressed(evt);
            }
        });

        partidaTxtM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        partidaTxtM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        partidaTxtM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                partidaTxtMKeyPressed(evt);
            }
        });

        duracaoTxtH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        duracaoTxtH.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duracaoTxtH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duracaoTxtHKeyPressed(evt);
            }
        });

        duracaoTxtM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        duracaoTxtM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        duracaoTxtM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                duracaoTxtMKeyPressed(evt);
            }
        });

        duracaoH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        duracaoH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        duracaoH.setText("Horas");

        duracaoM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        duracaoM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        duracaoM.setText("Minutos");

        chegadaH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chegadaH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chegadaH.setText("Horas");

        chegadaM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chegadaM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chegadaM.setText("Minutos");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Partida");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Chegada");

        chegadaTxtM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chegadaTxtM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chegadaTxtM.setText("?");

        chegadaTxtH.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chegadaTxtH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chegadaTxtH.setText("?");

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        msgFinal.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        msgFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(partidaTxtH, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(partidaH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(duracaoH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(duracaoTxtH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                                                .addGap(99, 99, 99)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(partidaTxtM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(partidaM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(duracaoTxtM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duracaoM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chegadaTxtH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chegadaH, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chegadaTxtM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chegadaM, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                        .addGap(61, 61, 61)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msgFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partidaH)
                    .addComponent(partidaM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partidaTxtH, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partidaTxtM, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duracaoH)
                    .addComponent(duracaoM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(duracaoTxtM)
                    .addComponent(duracaoTxtH, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chegadaH)
                            .addComponent(chegadaM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chegadaTxtH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chegadaTxtM, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Calculo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void partidaTxtHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partidaTxtHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partidaTxtHActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        partidaTxtH.setText("");
        partidaTxtM.setText("");
        chegadaTxtH.setText("");
        chegadaTxtM.setText("");
        duracaoTxtH.setText("");
        duracaoTxtM.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        
    }                               

    private void txt2KeyPressed(java.awt.event.KeyEvent evt) {                                
        
    }//GEN-LAST:event_jButton1KeyPressed

    private void partidaTxtHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_partidaTxtHKeyPressed
        validaKey(evt, partidaTxtH);
    }//GEN-LAST:event_partidaTxtHKeyPressed

    private void partidaTxtMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_partidaTxtMKeyPressed
        validaKey(evt, partidaTxtM);
    }//GEN-LAST:event_partidaTxtMKeyPressed

    private void duracaoTxtHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duracaoTxtHKeyPressed
        validaKey(evt, duracaoTxtH);
    }//GEN-LAST:event_duracaoTxtHKeyPressed

    private void duracaoTxtMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_duracaoTxtMKeyPressed
        validaKey(evt, duracaoTxtM);
    }//GEN-LAST:event_duracaoTxtMKeyPressed

    private void validaKey(java.awt.event.KeyEvent evt, JTextField txt) 
    {                                       
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == 8 || evt.getKeyCode() == 127)
        {
            txt.setEditable(true);
        }
        else
        {
            txt.setEditable(false);
        }
    }
    
    public void Calculo()
    {
        if (partidaTxtH.getText().length()==0 || partidaTxtM.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (duracaoTxtH.getText().length()==0 || duracaoTxtM.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (Integer.parseInt(partidaTxtH.getText()) > 23 || Integer.parseInt(duracaoTxtH.getText()) > 23 )
        {
            JOptionPane.showMessageDialog(null, "Horas entre 0 e 23.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (Integer.parseInt(partidaTxtH.getText()) > 59 || Integer.parseInt(duracaoTxtM.getText()) > 59)
        {
            JOptionPane.showMessageDialog(null, "Minutos entre 0 e 59.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (Integer.parseInt(partidaTxtH.getText()) < 0 || Integer.parseInt(duracaoTxtH.getText()) < 0 || Integer.parseInt(partidaTxtM.getText()) < 0 || Integer.parseInt(duracaoTxtM.getText()) < 0)
        {
            JOptionPane.showMessageDialog(null, "Não é permitido números negativos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int n1, n2, n3, n4, rHoras, rMinutos = 0;
        boolean novoDia = false;

        n1 = Integer.parseInt(partidaTxtH.getText());
        n2 = Integer.parseInt(partidaTxtM.getText());
        n3 = Integer.parseInt(duracaoTxtH.getText());
        n4 = Integer.parseInt(duracaoTxtM.getText());

        rHoras = n1 + n3;
        rMinutos = n2 + n4;
        
        if (rMinutos > 59)
        {
            rMinutos = rMinutos - 60;
            rHoras++;
        }
        
        if (rHoras > 23)
        {
            rHoras = rHoras - 24;
            novoDia = true;
        }
        
        chegadaTxtH.setText(String.format("%02d", rHoras));
        chegadaTxtM.setText(String.format("%02d", rMinutos));
        
        if (novoDia == true)
        {
            msgFinal.setText("O voo chegou no dia seguinte!");
        }
        else
        {
            msgFinal.setText("O voo chegou no próprio dia!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chegadaH;
    private javax.swing.JLabel chegadaM;
    private javax.swing.JLabel chegadaTxtH;
    private javax.swing.JLabel chegadaTxtM;
    private javax.swing.JLabel duracaoH;
    private javax.swing.JLabel duracaoM;
    private javax.swing.JTextField duracaoTxtH;
    private javax.swing.JTextField duracaoTxtM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel msgFinal;
    private javax.swing.JLabel partidaH;
    private javax.swing.JLabel partidaM;
    private javax.swing.JTextField partidaTxtH;
    private javax.swing.JTextField partidaTxtM;
    // End of variables declaration//GEN-END:variables
}
